// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: random_stall_service.proto

package dinningeasy

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Building int32

const (
	Building_INIT      Building = 0
	Building_QH        Building = 1
	Building_BH        Building = 2
	Building_KX        Building = 3
	Building_QE_ISLAND Building = 4
)

// Enum value maps for Building.
var (
	Building_name = map[int32]string{
		0: "INIT",
		1: "QH",
		2: "BH",
		3: "KX",
		4: "QE_ISLAND",
	}
	Building_value = map[string]int32{
		"INIT":      0,
		"QH":        1,
		"BH":        2,
		"KX":        3,
		"QE_ISLAND": 4,
	}
)

func (x Building) Enum() *Building {
	p := new(Building)
	*p = x
	return p
}

func (x Building) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Building) Descriptor() protoreflect.EnumDescriptor {
	return file_random_stall_service_proto_enumTypes[0].Descriptor()
}

func (Building) Type() protoreflect.EnumType {
	return &file_random_stall_service_proto_enumTypes[0]
}

func (x Building) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Building.Descriptor instead.
func (Building) EnumDescriptor() ([]byte, []int) {
	return file_random_stall_service_proto_rawDescGZIP(), []int{0}
}

type GetBuildingsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buildings []Building `protobuf:"varint,1,rep,packed,name=buildings,proto3,enum=trpc.easy_dinning.random_stalls.Building" json:"buildings,omitempty"`
}

func (x *GetBuildingsRsp) Reset() {
	*x = GetBuildingsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_stall_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBuildingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingsRsp) ProtoMessage() {}

func (x *GetBuildingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_random_stall_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingsRsp.ProtoReflect.Descriptor instead.
func (*GetBuildingsRsp) Descriptor() ([]byte, []int) {
	return file_random_stall_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetBuildingsRsp) GetBuildings() []Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

type GetBuildingsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBuildingsReq) Reset() {
	*x = GetBuildingsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_stall_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBuildingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildingsReq) ProtoMessage() {}

func (x *GetBuildingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_random_stall_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildingsReq.ProtoReflect.Descriptor instead.
func (*GetBuildingsReq) Descriptor() ([]byte, []int) {
	return file_random_stall_service_proto_rawDescGZIP(), []int{1}
}

type GetStallsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buildings []Building `protobuf:"varint,1,rep,packed,name=buildings,proto3,enum=trpc.easy_dinning.random_stalls.Building" json:"buildings,omitempty"`
}

func (x *GetStallsReq) Reset() {
	*x = GetStallsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_stall_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStallsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStallsReq) ProtoMessage() {}

func (x *GetStallsReq) ProtoReflect() protoreflect.Message {
	mi := &file_random_stall_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStallsReq.ProtoReflect.Descriptor instead.
func (*GetStallsReq) Descriptor() ([]byte, []int) {
	return file_random_stall_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetStallsReq) GetBuildings() []Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

type Stall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StallPicUrl string   `protobuf:"bytes,2,opt,name=stall_pic_url,json=stallPicUrl,proto3" json:"stall_pic_url,omitempty"`
	Tags        []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Desc        string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Loc         string   `protobuf:"bytes,5,opt,name=loc,proto3" json:"loc,omitempty"`
}

func (x *Stall) Reset() {
	*x = Stall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_stall_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stall) ProtoMessage() {}

func (x *Stall) ProtoReflect() protoreflect.Message {
	mi := &file_random_stall_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stall.ProtoReflect.Descriptor instead.
func (*Stall) Descriptor() ([]byte, []int) {
	return file_random_stall_service_proto_rawDescGZIP(), []int{3}
}

func (x *Stall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stall) GetStallPicUrl() string {
	if x != nil {
		return x.StallPicUrl
	}
	return ""
}

func (x *Stall) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Stall) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Stall) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

type GetStallsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stalls []*Stall `protobuf:"bytes,1,rep,name=stalls,proto3" json:"stalls,omitempty"`
}

func (x *GetStallsRsp) Reset() {
	*x = GetStallsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_random_stall_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStallsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStallsRsp) ProtoMessage() {}

func (x *GetStallsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_random_stall_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStallsRsp.ProtoReflect.Descriptor instead.
func (*GetStallsRsp) Descriptor() ([]byte, []int) {
	return file_random_stall_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetStallsRsp) GetStalls() []*Stall {
	if x != nil {
		return x.Stalls
	}
	return nil
}

var File_random_stall_service_proto protoreflect.FileDescriptor

var file_random_stall_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x74, 0x72,
	0x70, 0x63, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x5f, 0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x22, 0x5a, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x73, 0x70,
	0x12, 0x47, 0x0a, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x5f,
	0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x09,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x22, 0x57, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a, 0x09,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x5f, 0x64, 0x69, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x79, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x69, 0x63, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x63,
	0x22, 0x4e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x52, 0x73, 0x70,
	0x12, 0x3e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61, 0x73, 0x79, 0x5f, 0x64, 0x69, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73,
	0x2a, 0x3b, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x4e, 0x49, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x51, 0x48, 0x10, 0x01, 0x12, 0x06,
	0x0a, 0x02, 0x42, 0x48, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x4b, 0x58, 0x10, 0x03, 0x12, 0x0d,
	0x0a, 0x09, 0x51, 0x45, 0x5f, 0x49, 0x53, 0x4c, 0x41, 0x4e, 0x44, 0x10, 0x04, 0x32, 0xf3, 0x01,
	0x0a, 0x12, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x30, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61, 0x73, 0x79,
	0x5f, 0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x30, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61,
	0x73, 0x79, 0x5f, 0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x5f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x73, 0x70, 0x12, 0x69, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x2d, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61, 0x73,
	0x79, 0x5f, 0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x5f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x6c, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x61, 0x73, 0x79,
	0x5f, 0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x73,
	0x52, 0x73, 0x70, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4a, 0x69, 0x6e, 0x6c, 0x6b, 0x6a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x2f, 0x64, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x65, 0x61, 0x73, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_random_stall_service_proto_rawDescOnce sync.Once
	file_random_stall_service_proto_rawDescData = file_random_stall_service_proto_rawDesc
)

func file_random_stall_service_proto_rawDescGZIP() []byte {
	file_random_stall_service_proto_rawDescOnce.Do(func() {
		file_random_stall_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_random_stall_service_proto_rawDescData)
	})
	return file_random_stall_service_proto_rawDescData
}

var file_random_stall_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_random_stall_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_random_stall_service_proto_goTypes = []interface{}{
	(Building)(0),           // 0: trpc.easy_dinning.random_stalls.Building
	(*GetBuildingsRsp)(nil), // 1: trpc.easy_dinning.random_stalls.GetBuildingsRsp
	(*GetBuildingsReq)(nil), // 2: trpc.easy_dinning.random_stalls.GetBuildingsReq
	(*GetStallsReq)(nil),    // 3: trpc.easy_dinning.random_stalls.GetStallsReq
	(*Stall)(nil),           // 4: trpc.easy_dinning.random_stalls.Stall
	(*GetStallsRsp)(nil),    // 5: trpc.easy_dinning.random_stalls.GetStallsRsp
}
var file_random_stall_service_proto_depIdxs = []int32{
	0, // 0: trpc.easy_dinning.random_stalls.GetBuildingsRsp.buildings:type_name -> trpc.easy_dinning.random_stalls.Building
	0, // 1: trpc.easy_dinning.random_stalls.GetStallsReq.buildings:type_name -> trpc.easy_dinning.random_stalls.Building
	4, // 2: trpc.easy_dinning.random_stalls.GetStallsRsp.stalls:type_name -> trpc.easy_dinning.random_stalls.Stall
	2, // 3: trpc.easy_dinning.random_stalls.RandomStallService.GetBuildings:input_type -> trpc.easy_dinning.random_stalls.GetBuildingsReq
	3, // 4: trpc.easy_dinning.random_stalls.RandomStallService.GetStalls:input_type -> trpc.easy_dinning.random_stalls.GetStallsReq
	1, // 5: trpc.easy_dinning.random_stalls.RandomStallService.GetBuildings:output_type -> trpc.easy_dinning.random_stalls.GetBuildingsRsp
	5, // 6: trpc.easy_dinning.random_stalls.RandomStallService.GetStalls:output_type -> trpc.easy_dinning.random_stalls.GetStallsRsp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_random_stall_service_proto_init() }
func file_random_stall_service_proto_init() {
	if File_random_stall_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_random_stall_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBuildingsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_random_stall_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBuildingsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_random_stall_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStallsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_random_stall_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_random_stall_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStallsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_random_stall_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_random_stall_service_proto_goTypes,
		DependencyIndexes: file_random_stall_service_proto_depIdxs,
		EnumInfos:         file_random_stall_service_proto_enumTypes,
		MessageInfos:      file_random_stall_service_proto_msgTypes,
	}.Build()
	File_random_stall_service_proto = out.File
	file_random_stall_service_proto_rawDesc = nil
	file_random_stall_service_proto_goTypes = nil
	file_random_stall_service_proto_depIdxs = nil
}
